/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    restaurants: Restaurant;
    categories: Category;
    dishes: Dish;
    media: Media;
    scans: Scan;
    'scan-photos': ScanPhoto;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    restaurants: RestaurantsSelect<false> | RestaurantsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    dishes: DishesSelect<false> | DishesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    scans: ScansSelect<false> | ScansSelect<true>;
    'scan-photos': ScanPhotosSelect<false> | ScanPhotosSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: number;
  name: string;
  /**
   * Se completa solo a partir del nombre. Solo minúsculas, números y guiones.
   */
  slug: string;
  /**
   * Aparece debajo del logo.
   */
  tagline?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  hero?: (number | null) | Media;
  /**
   * Se genera un QR por mesa.
   */
  tables?: number | null;
  currency?: ('PYG' | 'USD') | null;
  /**
   * Ej.: 0976 145 539. Si está vacío, el menú no muestra el botón «Enviar pedido por WhatsApp».
   */
  whatsapp?: string | null;
  orderTypes?: ('delivery' | 'pickup')[] | null;
  paymentMethods?: ('efectivo' | 'transferencia' | 'qr' | 'tarjeta')[] | null;
  /**
   * En guaraníes. Vacío = «a confirmar». Si cargás zonas, se usa el de la zona.
   */
  deliveryFee?: number | null;
  /**
   * En guaraníes, sin contar el envío. Vacío = sin mínimo.
   */
  minOrder?: number | null;
  /**
   * Opcional. Ej.: Centro ₲ 10.000, Lambaré ₲ 15.000.
   */
  deliveryZones?:
    | {
        name: string;
        fee: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Se muestran si el cliente elige transferencia o QR. Ej.: Alias 0981 123 456 · Banco… · a nombre de…
   */
  transferInfo?: string | null;
  /**
   * Hora de Paraguay. Si cierra después de medianoche, poné la hora de cierre igual (ej.: 18:00 a 02:00). Vacío = siempre abierto.
   */
  hours?:
    | {
        days: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[];
        open: string;
        close: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej.: Pizza, Parrilla. Ayuda en Google.
   */
  cuisine?: string[] | null;
  theme?: {
    primary?: string | null;
    primaryLight?: string | null;
    background?: string | null;
    accentWine?: string | null;
  };
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotos de platos (PNG con fondo transparente se ven mejor) y modelos 3D (.glb).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Restaurant;
  /**
   * Qué se ve en la imagen (ayuda a personas con lector de pantalla).
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Arrastrá las filas para cambiar el orden en el menú.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  tenant?: (number | null) | Restaurant;
  name: string;
  /**
   * Se completa solo a partir del nombre. Solo minúsculas, números y guiones.
   */
  slug: string;
  /**
   * Ej.: "Guarniciones incluidas: …"
   */
  description?: string | null;
  cover?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Arrastrá las filas para cambiar el orden dentro de cada categoría.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dishes".
 */
export interface Dish {
  id: number;
  _order?: string | null;
  tenant?: (number | null) | Restaurant;
  name: string;
  /**
   * En guaraníes, sin puntos. Vacío = no se publica.
   */
  price?: number | null;
  category: number | Category;
  description?: string | null;
  /**
   * Escribí cada ingrediente y Enter.
   */
  ingredients?: string[] | null;
  /**
   * Con significado en el menú: destacado, para compartir, picante, sin gluten, sin alcohol, vegetariano, de la casa, extra. En vinos, cualquier dato: tinto, Rioja, Malbec…
   */
  tags?: string[] | null;
  /**
   * Ej.: Tamaño → Mediana, Grande (+₲ 15.000). Extras → Cheddar (+₲ 5.000), Panceta (+₲ 7.000).
   */
  options?:
    | {
        group: string;
        multiple?: boolean | null;
        /**
         * El cliente tiene que elegir al menos una.
         */
        required?: boolean | null;
        items?:
          | {
              name: string;
              /**
               * En guaraníes. 0 = sin cargo.
               */
              price?: number | null;
              id?: string | null;
            }[]
          | null;
        choices?: string[] | null;
        id?: string | null;
      }[]
    | null;
  photo?: (number | null) | Media;
  model?: (number | null) | Media;
  /**
   * Ej.: "Modelo de demostración".
   */
  modelNote?: string | null;
  /**
   * Se completa solo a partir del nombre. Solo minúsculas, números y guiones.
   */
  slug: string;
  visible?: boolean | null;
  /**
   * Se ve en el menú, marcado como agotado.
   */
  soldOut?: boolean | null;
  /**
   * No se publica.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotos de un plato → modelo 3D. Se empieza desde el plato: «Generar 3D desde fotos».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scans".
 */
export interface Scan {
  id: number;
  tenant?: (number | null) | Restaurant;
  title?: string | null;
  dish?: (number | null) | Dish;
  /**
   * Medilo con una regla. En realidad aumentada el plato aparece con este tamaño.
   */
  diameterCm?: number | null;
  /**
   * Plato sobre una mesa con textura (mantel, madera), buena luz y sin moverlo. Tres vueltas: baja, a media altura y desde arriba. Que cada foto se superponga con la anterior. Se borran al terminar.
   */
  photos?: (number | ScanPhoto)[] | null;
  /**
   * Vacío = todavía no se generó.
   */
  status?: ('queued' | 'processing' | 'done' | 'failed') | null;
  runUrl?: string | null;
  result?: string | null;
  error?: string | null;
  requestedAt?: string | null;
  finishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-photos".
 */
export interface ScanPhoto {
  id: number;
  tenant?: (number | null) | Restaurant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'staff';
  tenants?:
    | {
        tenant: number | Restaurant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'restaurants';
        value: number | Restaurant;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'dishes';
        value: number | Dish;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'scans';
        value: number | Scan;
      } | null)
    | ({
        relationTo: 'scan-photos';
        value: number | ScanPhoto;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants_select".
 */
export interface RestaurantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  hero?: T;
  tables?: T;
  currency?: T;
  whatsapp?: T;
  orderTypes?: T;
  paymentMethods?: T;
  deliveryFee?: T;
  minOrder?: T;
  deliveryZones?:
    | T
    | {
        name?: T;
        fee?: T;
        id?: T;
      };
  transferInfo?: T;
  hours?:
    | T
    | {
        days?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  cuisine?: T;
  theme?:
    | T
    | {
        primary?: T;
        primaryLight?: T;
        background?: T;
        accentWine?: T;
      };
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  cover?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dishes_select".
 */
export interface DishesSelect<T extends boolean = true> {
  _order?: T;
  tenant?: T;
  name?: T;
  price?: T;
  category?: T;
  description?: T;
  ingredients?: T;
  tags?: T;
  options?:
    | T
    | {
        group?: T;
        multiple?: T;
        required?: T;
        items?:
          | T
          | {
              name?: T;
              price?: T;
              id?: T;
            };
        choices?: T;
        id?: T;
      };
  photo?: T;
  model?: T;
  modelNote?: T;
  slug?: T;
  visible?: T;
  soldOut?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scans_select".
 */
export interface ScansSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  dish?: T;
  diameterCm?: T;
  photos?: T;
  status?: T;
  runUrl?: T;
  result?: T;
  error?: T;
  requestedAt?: T;
  finishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-photos_select".
 */
export interface ScanPhotosSelect<T extends boolean = true> {
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}