"""Build the Gringo Bar seed from the material in gringodatos/ + menu.json.

Sources (gringodatos/, not in the repo):
  burguerdelacasa.jpg   Instagram post of the house burger (1080×1350)
  Multimedia (12).jpg   Instagram post, 14/04/2023: "Pizzas de masa madre" menu with prices
  Multimedia (13).jpg   Story "Gringo Eventos", 28/04/2024: logo, brand colors, phone
  Multimedia (14).jpg   Story "Gringo menú", 20/08/2025: "Menú Drinks" with prices

Outputs (idempotent, deterministic UUIDs):
  images/logo-blanco.png          circular badge, white on transparent (from the Eventos story)
  images/burguer-de-la-casa.png   house burger, cropped and feathered to transparent (dish photo)
  images/pizza-gringo-demo.png    trimmed (rendered by make_models.py; placeholder)
  seed.sql                        INSERTs for db/schema.sql (tenant, restaurant, categories, dishes, media)

Usage:  python seed/gringo-bar/build.py            (from repo root)
Requires: pip install pillow
"""
import hashlib
import json
import pathlib
import uuid

from PIL import Image, ImageChops, ImageDraw, ImageFilter

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent.parent
SRC = ROOT / "gringodatos"
IMG_DIR = HERE / "images"
NS = uuid.UUID("6f1c9c2e-3d7a-4b8e-9a51-0f1b2c3d4e5f")  # same seed namespace as filigrana
BUCKET = "media-public"


def uid(*parts: str) -> str:
    return str(uuid.uuid5(NS, "/".join(parts)))


def q(v) -> str:
    """SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        inner = ",".join('"' + x.replace("\\", "\\\\").replace('"', '\\"') + '"' for x in v)
        return "'{" + inner.replace("'", "''") + "}'"
    return "'" + str(v).replace("'", "''") + "'"


def qj(v) -> str:
    """jsonb literal."""
    return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def trim(im: Image.Image) -> Image.Image:
    bbox = im.getchannel("A").getbbox()
    return im.crop(bbox) if bbox else im


def logo() -> Image.Image:
    """White badge from the Eventos story: luminance → alpha, outside the badge is cut."""
    g = Image.open(SRC / "Multimedia (13).jpg").convert("L").crop((95, 1262, 540, 1640))
    g = g.resize((g.width * 2, g.height * 2), Image.LANCZOS)
    alpha = g.point(lambda v: 0 if v < 105 else 255 if v > 190 else int((v - 105) * 255 / 85))
    # keep only the badge (circle + star ribbon) so the wood texture never leaks in
    keep = Image.new("L", g.size, 0)
    d = ImageDraw.Draw(keep)
    cx, cy, r = g.width * 0.5, g.height * 0.53, g.height * 0.47
    d.ellipse((cx - r, cy - r, cx + r, cy + r), fill=255)
    d.rectangle((0, cy - r * 0.36, g.width, cy + r * 0.05), fill=255)
    alpha = ImageChops.multiply(alpha, keep)
    im = Image.new("RGBA", g.size, (255, 255, 255, 0))
    im.putalpha(alpha)
    return trim(im)


def burger() -> Image.Image:
    """House burger without the post's headline and the hand, edges fading to transparent."""
    im = Image.open(SRC / "burguerdelacasa.jpg").convert("RGB").crop((150, 372, 970, 1150))
    mask = Image.new("L", im.size, 0)
    ImageDraw.Draw(mask).ellipse((40, 20, im.width - 40, im.height - 30), fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(38))
    out = im.convert("RGBA")
    out.putalpha(mask)
    return trim(out)


def pizza_poster() -> Image.Image:
    return trim(Image.open(IMG_DIR / "pizza-gringo-demo.png").convert("RGBA"))


def build_images(alts: dict) -> dict:
    IMG_DIR.mkdir(exist_ok=True)
    meta = {}
    for name, make in (("logo-blanco", logo), ("burguer-de-la-casa", burger), ("pizza-gringo-demo", pizza_poster)):
        im = make()
        im.save(IMG_DIR / f"{name}.png", optimize=True)
        web = im.copy()
        web.thumbnail((1600, 1600), Image.LANCZOS)
        data = _webp_bytes(web)
        meta[name] = {"width": web.width, "height": web.height, "bytes": len(data),
                      "sha256": hashlib.sha256(data).hexdigest(), "alt": alts.get(name, name.replace("-", " "))}
    return meta


def _webp_bytes(im: Image.Image) -> bytes:
    import io
    buf = io.BytesIO()
    im.save(buf, "WEBP", quality=85, method=6)
    return buf.getvalue()


def build_sql(m: dict, meta: dict) -> str:
    t_id = uid("tenant", m["tenant"]["slug"])
    r = m["restaurant"]
    r_id = uid("restaurant", r["slug"])
    media_id = {name: uid("media", r["slug"], name) for name in meta}
    out = [
        "-- Generated by seed/gringo-bar/build.py — do not edit by hand.",
        "-- Source: " + m["$source"],
        "BEGIN;",
        f"INSERT INTO tenants (id, name, slug) VALUES ({q(t_id)}, {q(m['tenant']['name'])}, {q(m['tenant']['slug'])}) ON CONFLICT (id) DO NOTHING;",
    ]
    for name, mt in meta.items():
        key = f"t/{t_id}/restaurants/{r_id}/{name}-{media_id[name][:8]}.webp"
        out.append(
            "INSERT INTO media (id, tenant_id, kind, bucket, storage_key, mime, bytes, sha256, width, height, alt) VALUES "
            f"({q(media_id[name])}, {q(t_id)}, 'image', {q(BUCKET)}, {q(key)}, 'image/webp', {mt['bytes']}, {q(mt['sha256'])}, "
            f"{mt['width']}, {mt['height']}, {q(mt['alt'])}) ON CONFLICT (id) DO NOTHING;"
        )
    out.append(
        "INSERT INTO restaurants (id, tenant_id, name, slug, description, logo_id, cover_id, currency, default_locale, theme, status) VALUES "
        f"({q(r_id)}, {q(t_id)}, {q(r['name'])}, {q(r['slug'])}, {q(r['description'])}, {q(media_id[r['logo']])}, "
        f"{q(media_id.get(r.get('hero')))}, {q(r['currency'])}, {q(r['default_locale'])}, {qj(r['theme'])}, 'draft') ON CONFLICT (id) DO NOTHING;"
    )
    for ci, c in enumerate(m["categories"]):
        c_id = uid("category", r["slug"], c["slug"])
        out.append(
            "INSERT INTO categories (id, tenant_id, restaurant_id, name, slug, description, cover_id, position) VALUES "
            f"({q(c_id)}, {q(t_id)}, {q(r_id)}, {q(c['name'])}, {q(c['slug'])}, {q(c.get('description'))}, "
            f"{q(media_id.get(c.get('cover')))}, {ci * 10}) ON CONFLICT (id) DO NOTHING;"
        )
        for di, d in enumerate(c["dishes"]):
            d_id = uid("dish", r["slug"], d["slug"])
            status = d.get("status") or ("draft" if d.get("price") is None else "published")
            out.append(
                "INSERT INTO dishes (id, tenant_id, restaurant_id, category_id, name, slug, description, ingredients, tags, options, price_minor, position, status) VALUES "
                f"({q(d_id)}, {q(t_id)}, {q(r_id)}, {q(c_id)}, {q(d['name'])}, {q(d['slug'])}, {q(d.get('description'))}, "
                f"{q(d.get('ingredients', []))}, {q(d.get('tags', []))}, {qj(d.get('options', []))}, {q(d.get('price'))}, "
                f"{di * 10}, {q(status)}) ON CONFLICT (id) DO NOTHING;"
            )
            if photo := d.get("photo"):
                out.append(
                    f"INSERT INTO dish_photos (dish_id, media_id, tenant_id, position) VALUES ({q(d_id)}, {q(media_id[photo])}, {q(t_id)}, 0) ON CONFLICT DO NOTHING;"
                )
    out.append("COMMIT;")
    return "\n".join(out) + "\n"


def main():
    m = json.loads((HERE / "menu.json").read_text(encoding="utf-8"))
    meta = build_images({"logo-blanco": "logo Gringo Bar (fondo oscuro)",
                         "burguer-de-la-casa": "burguer de la casa",
                         "pizza-gringo-demo": "pizza Gringo (render de demostración)"})
    (HERE / "seed.sql").write_text(build_sql(m, meta), encoding="utf-8")
    dishes = [d for c in m["categories"] for d in c["dishes"]]
    print(f"{len(meta)} images, {len(m['categories'])} categories, {len(dishes)} dishes, "
          f"{sum(1 for d in dishes if d.get('photo'))} with photo, {sum(1 for d in dishes if d.get('review'))} to review")


if __name__ == "__main__":
    main()
