"""Build the Filigrana seed from the original Canva PDF + menu.json.

Outputs (idempotent, deterministic UUIDs):
  images/<name>.png   lossless master, transparent background, trimmed
  images/<name>.webp  web version (max 1600 px, alpha kept)
  seed.sql            INSERTs for db/schema.sql (tenant, restaurant, categories, dishes, media)

Usage:  python seed/filigrana/build.py            (from repo root)
Requires: pip install pymupdf pillow
"""
import hashlib
import json
import pathlib
import uuid

import pymupdf
from PIL import Image

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent.parent
PDF = ROOT / "Filigrana oficio (22 x 33 cm).pdf"
IMG_DIR = HERE / "images"
NS = uuid.UUID("6f1c9c2e-3d7a-4b8e-9a51-0f1b2c3d4e5f")  # seed namespace
MAX_EDGE = 1600
BUCKET = "media-public"


def uid(*parts: str) -> str:
    return str(uuid.uuid5(NS, "/".join(parts)))


def q(v) -> str:
    """SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        inner = ",".join('"' + x.replace("\\", "\\\\").replace('"', '\\"') + '"' for x in v)
        return "'{" + inner.replace("'", "''") + "}'"
    return "'" + str(v).replace("'", "''") + "'"


def qj(v) -> str:
    """jsonb literal."""
    return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def extract_images(doc, images: dict) -> dict:
    IMG_DIR.mkdir(exist_ok=True)
    meta = {}
    for name, spec in images.items():
        xref = spec["xref"]
        smask = next(img[1] for page in doc for img in page.get_images(full=True) if img[0] == xref)
        pix = pymupdf.Pixmap(doc, xref)
        if smask:
            pix = pymupdf.Pixmap(pix, pymupdf.Pixmap(doc, smask))
        im = Image.frombytes("RGBA" if pix.alpha else "RGB", (pix.width, pix.height), pix.samples)
        if im.mode == "RGBA" and (bbox := im.getchannel("A").getbbox()):
            im = im.crop(bbox)  # trim transparent margins
        im.save(IMG_DIR / f"{name}.png", optimize=True)
        web = im.copy()
        web.thumbnail((MAX_EDGE, MAX_EDGE), Image.LANCZOS)
        web_path = IMG_DIR / f"{name}.webp"
        web.save(web_path, "WEBP", quality=85, method=6)
        data = web_path.read_bytes()
        meta[name] = {
            "width": web.width,
            "height": web.height,
            "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
            "alt": spec.get("use") or name.replace("-", " "),
        }
    return meta


def build_sql(m: dict, meta: dict) -> str:
    t_id = uid("tenant", m["tenant"]["slug"])
    r = m["restaurant"]
    r_id = uid("restaurant", r["slug"])
    media_id = {name: uid("media", name) for name in meta}
    out = [
        "-- Generated by seed/filigrana/build.py — do not edit by hand.",
        "-- Source: " + m["$source"],
        "BEGIN;",
        f"INSERT INTO tenants (id, name, slug) VALUES ({q(t_id)}, {q(m['tenant']['name'])}, {q(m['tenant']['slug'])}) ON CONFLICT (id) DO NOTHING;",
    ]
    for name, mt in meta.items():
        key = f"t/{t_id}/restaurants/{r_id}/{name}-{media_id[name][:8]}.webp"
        out.append(
            "INSERT INTO media (id, tenant_id, kind, bucket, storage_key, mime, bytes, sha256, width, height, alt) VALUES "
            f"({q(media_id[name])}, {q(t_id)}, 'image', {q(BUCKET)}, {q(key)}, 'image/webp', {mt['bytes']}, {q(mt['sha256'])}, "
            f"{mt['width']}, {mt['height']}, {q(mt['alt'])}) ON CONFLICT (id) DO NOTHING;"
        )
    out.append(
        "INSERT INTO restaurants (id, tenant_id, name, slug, description, logo_id, cover_id, currency, default_locale, theme, status) VALUES "
        f"({q(r_id)}, {q(t_id)}, {q(r['name'])}, {q(r['slug'])}, {q(r['description'])}, {q(media_id[r['logo']])}, "
        f"{q(media_id[r['cover']])}, {q(r['currency'])}, {q(r['default_locale'])}, {qj(r['theme'])}, 'draft') ON CONFLICT (id) DO NOTHING;"
    )
    for ci, c in enumerate(m["categories"]):
        c_id = uid("category", r["slug"], c["slug"])
        out.append(
            "INSERT INTO categories (id, tenant_id, restaurant_id, name, slug, description, cover_id, position) VALUES "
            f"({q(c_id)}, {q(t_id)}, {q(r_id)}, {q(c['name'])}, {q(c['slug'])}, {q(c.get('description'))}, "
            f"{q(media_id.get(c.get('cover')))}, {ci * 10}) ON CONFLICT (id) DO NOTHING;"
        )
        for di, d in enumerate(c["dishes"]):
            d_id = uid("dish", r["slug"], d["slug"])
            status = d.get("status") or ("draft" if d.get("price") is None else "published")
            out.append(
                "INSERT INTO dishes (id, tenant_id, restaurant_id, category_id, name, slug, description, ingredients, tags, options, price_minor, position, status) VALUES "
                f"({q(d_id)}, {q(t_id)}, {q(r_id)}, {q(c_id)}, {q(d['name'])}, {q(d['slug'])}, {q(d.get('description'))}, "
                f"{q(d.get('ingredients', []))}, {q(d.get('tags', []))}, {qj(d.get('options', []))}, {q(d.get('price'))}, "
                f"{di * 10}, {q(status)}) ON CONFLICT (id) DO NOTHING;"
            )
            if photo := d.get("photo"):
                out.append(
                    f"INSERT INTO dish_photos (dish_id, media_id, tenant_id, position) VALUES ({q(d_id)}, {q(media_id[photo])}, {q(t_id)}, 0) ON CONFLICT DO NOTHING;"
                )
    out.append("COMMIT;")
    return "\n".join(out) + "\n"


def main():
    m = json.loads((HERE / "menu.json").read_text(encoding="utf-8"))
    doc = pymupdf.open(PDF)
    meta = extract_images(doc, m["images"])
    (HERE / "seed.sql").write_text(build_sql(m, meta), encoding="utf-8")
    dishes = [d for c in m["categories"] for d in c["dishes"]]
    print(f"{len(meta)} images, {len(m['categories'])} categories, {len(dishes)} dishes, "
          f"{sum(1 for d in dishes if d.get('photo'))} with photo, {sum(1 for d in dishes if d.get('review'))} to review")


if __name__ == "__main__":
    main()
